# sample dev block in the toml
# note: each of these fields are OPTIONAL and should only be used if you need an override
[dev]
  publish = "src/site" # If you use a _redirect file, provide the path to your static content folder

  functions = ".netlify/functions"